[package]
name = "libdragon-rs-template"
version = "0.1.0"
edition = "2021"
build = "build.rs"
rust-version = "1.75.0"

[dependencies]
libdragon = { path = "./libdragon-rs/libdragon" }

[build-dependencies]
libdragon-build = { path = "./libdragon-rs/libdragon-build" }
